README.md

I think this needs to be updated to be in line with #5

changed eslint.json reference to .eslintrc

---

CHANGELOG.md
package.json

I think the changes that we introduced in #53 are enough to satisfy a minor version bump. I'll publish after merging the package change and tagging.

Update changelog and bump package version

---

config/eslint-tests.js
config/eslint.js
package.json
tests/dummy/app/controllers/.eslintrc

Follow up to https://github.com/ember-cli/ember-cli-eslint/pull/53

Remove eslint-config-ember from package

---

index.js

This builds upon changes in broccoli-lint-eslint (https://github.com/ember-cli/broccoli-lint-eslint/pull/38) to add a third argument that is the underlying ESLint results object. With this, we can determine pass/fail based on `results.errorCount` (and not just the presence of messages).  Using messages alone is not sufficient, because it intermingles errors and warnings.
Fixes #66.

Update the default `testGenerator` to avoid erroring on warnings.

---

blueprints/ember-cli-eslint/index.js
package.json

Uninstall `ember-cli-jshint` after addon installation

---

.travis.yml
node-tests/blueprints/ember-cli-eslint-test.js
package.json

/cc @alexlafroscia @trabus @stefanpenner @rwjblue @BrianSipple

Add tests for the "ember-cli-eslint" blueprint

---

.travis.yml
ember-cli-build.js
node-tests/test.js
package.json

similar to https://github.com/ember-cli/ember-cli-jshint/pull/19
/cc @BrianSipple @alexlafroscia @rwjblue

Add tests for the "ember test" output

---

node-tests/.eslintrc.js
node-tests/test.js

My atom complains about eslint errors in node-tests dir

Add .eslintrc for node-tests

---

blueprints/ember-cli-eslint/index.js

Blueprint cleanup

---

README.md

Adds a note about linting addons. @Turbo87 thoughts on the wording?
closes #154

update readme: add note about linting addons

---

package.json

chore(package): update ember-cli-blueprint-test-helpers to version 0.17.1

---

ember-cli-build.js
index.js
node-tests/test.js
package.json

Resolves #146 
see https://github.com/ember-cli/broccoli-lint-eslint/pull/95

Use new "group" option of "broccoli-lint-eslint" by default

---

.travis.yml

see https://github.com/Turbo87/auto-dist-tag

CI: Use "auto-dist-tag" for deployment

---

package.json

chore(package): update testdouble to version 3.1.0

---

package.json

chore(package): update ember-cli-htmlbars to version 2.0.2

---

package.json
yarn.lock

to address https://github.com/ember-cli/ember-cli/issues/7347

Update `broccoli-lint-eslint` to v4.2.1

---

.travis.yml
package.json
yarn.lock

Drop support for node 4

---

tests/dummy/config/targets.js

Drop support for IE9 and IE10 in dummy app

---

package.json
yarn.lock

Breaking.
Will update once broccoli-lint-eslint 5 is released to point to the release.

Upgrade `broccoli-lint-eslint` to v5.0.0

---

index.js

Expose `format` property
