README.md
index.js
package.json

**Do not merge - depends on a custom broccoli-lint-eslint branch**
----
Depends on https://github.com/jonathanKingston/broccoli-lint-eslint/pull/2
I added an empty test generator because I'm not sure if you'd like to pick a default testing framework (which should probably be qunit since it is ember-cli's default).
Here is my test generator. I will happily add it to this PR if you' d like.
```javascript
var app = new EmberApp({
eslint: {
testGenerator: eslintTestGenerator
}
});
function eslintTestGenerator(relativePath, errors) {
var pass = !errors || errors.length === 0;
return "module('ESLINT - " + path.dirname(relativePath) + "');\n" +
"test('" + relativePath + " should pass eslint', function() {\n" +
"  ok(" + pass + ", '" + relativePath + " should pass eslint." + …
```

Add test generator support

---

index.js

This prevents running both JSHint and ESLint.
As of https://github.com/ember-cli/ember-cli-qunit/pull/102 ember-cli-qunit's `lintTree` hook is disabled when this property is present on another addon.

Disable ember-cli-qunit's lintTree hook.

---

.travis.yml
blueprints/ember-cli-eslint/index.js
package.json
tests/index.html

This addresses issues #20 and #28.  
Regarding #20:
Currently the `0.0.5` version of `eslint-config-ember` that `ember-cli-eslint` extends is using a version of `eslint` prior to 1.0. This seems to lead to error messages during `ember-cli-eslint`'s linter phase stating things such as: `error  Rule 'no-comma-dangle' was removed and replaced by: comma-dangle`.
Since `eslint-config-ember` itself has long-since been updated to use a version of `eslint` > 1.0, this should clear up those issues.
Regarding #28:
This was an issue for me both locally and in CI. 
It seems reasonable that the dev-dependency should use the latest of the "Valid install targets". Once I made this change, I started seeing an error in Travis stating `DEPRECATION: Node v0.10.42 is no longer supported by Ember CLI. Please …

Updated to install latest version of eslint-config-ember

---

index.js
package.json

This PR will make use of the `Project.generateTestFile()` method by default if available (introduced by ember-cli/ember-cli#5508).

Use project.generateTestFile() if available

---

package.json
tests/index.html

This PR addresses #34 where tests weren't being transpiled. 
Somewhere along the way in the last few commits, we seem to have accidentally declared the `dependencies` hash in `package.json` twice. The last one wins... and it was the one without `ember-cli-babel` :flushed:.
There was also a duplicate `assets/tests.js` script inside of `tests/index.html` that I took care of deleting. 
These changes should get us green in CI.

Fix declaration of "dependencies" in package.json

---

README.md

While the configurability of specifying a test generator function manually is really great, it also makes setting up this plugin trickier than it has to be and thus harder to get started with.  This change allows a user to specify a `testFramework` option (which defaults to `qunit`) that will automatically add the test generator to `ember test`, since that is most likely the behavior that they want.  They can still specify the generator function manually, but no longer have to.
Currently, this supports `qunit` or `mocha` frameworks, since I grabbed the example functions from the README and used those.  I tested this against the `ember-ajax` addon, which I've been porting to use `ember-cli-eslint` over the last few days; the resulting configuration is much cleaner: the default …

Update documentation to reflect easier configuration

---

blueprints/ember-cli-eslint/index.js
package.json

This PR is meant to coincide with https://github.com/jonathanKingston/ember-cli-eslint/pull/39/files and depends on getting `eslint-config-ember` to 0.3.0 with https://github.com/jonathanKingston/eslint-config-ember/pull/7. 
It ensures that the `eslint-config-ember` package we're adding to consumer projects is also at  0.3.0, and I also added logic for `afterUninstall` that cleans up the package if some decides to uninstall.

update eslint-config-ember version installed by addon and add `afterUninstall` hook

---

config/release.js
package.json

To address #49, I drafted a release for the current version of the package (1.2.1), and also updated to the latest version of [ember-cli-relase](https://github.com/lytics/ember-cli-release) with the hopes that we can use it going forward. 
Also, I was trying to see if I could draft a release for 1.2.0 by using the [commit hash from when that became the latest version](https://github.com/jonathanKingston/ember-cli-eslint/commit/5aba58a83e8ad36be5bd781c6afe911ff40d9fa6), but the selection tool on the release drafting page only exposes "Recent Commits" -- which apparently doesn't go as far back as our 1.2.0 bump. If anyone knows how to draft a release for _any_ specific commit, I'd be super curious to know how. At the very least, though, these changes will put us on the right track going …

Install latest version of ember-cli-release (1.1.0-beta.1)

---

index.js

Don't attempt to lint the template tree.
This will fix build failure caused by merging jonathanKingston/broccoli-lint-eslint#25.

Don't lint the template tree

---

config/eslint.js
tests/dummy/app/app.js
tests/dummy/app/controllers/thing.js

Looks like [travis-build](https://travis-ci.org/jonathanKingston/ember-cli-eslint) is broken on master branch. Changing a little bit the rules and adding this `const` should lint better (the lint addon, pun-intended).
Thanks for detecting this @pfmmfp !

Fixed eslint tests broken on Travis

---

config/eslint-tests.js

This is minor change to follow-up on https://github.com/jonathanKingston/ember-cli-eslint/pull/47.
Now that `broccoli-lint-eslint` has been updated to detect nested configs, the config being used in the dummy app is -- as it's supposed to -- overriding the root... and so the additions made in #47 don't quite cover everything in the dummy app. 
I plan to do a bit more refactoring into how our local linting set up, but I just wanted to get this in as a minor change before bumping to `1.3.0`.

Update rules used by dummy app to fix test linting

---

README.md

`ember-cli-2.5.0` made disabling JSHint and using ESLint [fantastically easier](https://github.com/ember-cli/ember-cli/pull/5757). Now, though, having a few projects ahead and behind 2.5 that are all using `ember-cli-eslint`, I realized that it would be really useful to document the strategies from both eras. 
Would anyone mind a quick proofread to make sure everything is correct? (cc: 
@rwjblue @Turbo87 @alexlafroscia) 
Possibly helpful:
* https://github.com/ember-cli/ember-cli-eslint/issues/7
* https://github.com/ember-cli/ember-cli-eslint/issues/57

Document Disabling JSHint

---

package.json

Since Ember's universal [recommendation](https://guides.emberjs.com/v2.5.0/getting-started/#toc_phantomjs-optional) is for users to have PhantomJS installed globally on their machines -- should they choose to use it at all -- it seems out of place for us to be requiring in our `devDepencencies`. 
Install-time slowdowns not even withstanding, it seems like doing this is only risking creating unexpected behaviors by going against most other Ember addons and applications out there.

Remove phantomJS from devDependencies

---

.npmignore
.travis.yml
bower.json
config/ember-try.js
package.json
testem.js
tests/helpers/module-for-acceptance.js

This PR updates the project to `ember-cli` @ 2.6.1 and makes the appropriate [changes from 2.3.1](https://github.com/ember-cli/ember-cli/releases). 
Mainly...
* Convert `testem.json` to `testem.js`
* Adding ember-try scenario for `1.13`
* Update minor & patch versions of various dependencies in `package.json`
* Update `npm test` command to run `ember try:each`
* Update `.travis.yml` to the latest structure

Update dependencies and project structure for Ember-CLI 2.6.1

---

blueprints/ember-cli-eslint/files/.eslintrc.js
index.js

With the way `.eslintrc.js` tries to extend from `./node_modules/ember-cli-eslint/coding-standard/ember-application.js`, I'm getting resolution errors stemming from the fact that eslint is being run from within ember-cli-eslint.
When serving after generating a new app and installing `ember-cli-eslint`:
```
The Broccoli Plugin: [EslintValidationFilter] failed with:
Error: Cannot read config file: /Users/bsipple/fooApp/node_modules/node_modules/ember-cli-eslint/coding-standard/ember-application.js
Error: Cannot find module '/Users/bsipple/fooApp/node_modules/node_modules/ember-cli-eslint/coding-standard/ember-application.js'
Referenced from: /Users/bsipple/fooApp/.eslintrc.js
```
I'm not sure why I didn't see this when developing the change -- I might have had `eslint` installed locally -- …

Use path.join for relative path resolution

---

blueprints/ember-cli-eslint/files/.eslintrc.js
blueprints/ember-cli-eslint/files/tests/.eslintrc.js

According to this [commit](https://github.com/ember-cli/ember-cli-eslint/commit/d1c3c4408f64e07b3ee274a991cab9ee318085b6) I think that `require.resolve` should be used here too.

Resolve Ember Testing coding standard

---

index.js

This passes a `console` object in the options object passed to broccoli-lint-eslint (see https://github.com/ember-cli/broccoli-lint-eslint/pull/51).
This means that broccoli-lint-eslint can respect the `--silent` option by using this object over the `console` global.
I was able to test this in a project that uses `ember-cli-eslint` by npm-linking ember-cli-eslint and broccoli-lint-eslint locally:
This should be a non-breaking change, but we may want to co-ordinate this with a version bump in broccoli-lint-eslint.

Pass console object that wraps this.ui

---

package.json

Removes the `ember-ajax` dependency, which we don't need, as @Turbo87 pointed out in #104

Remove unnecessary `ember-ajax` dependency

---

README.md
blueprints/ember-cli-eslint/files/.eslintrc.js
blueprints/ember-cli-eslint/files/tests/.eslintrc.js

*Note:* This is definitely a breaking change that will require a major
version bump and a note in the `CHANGELOG` about the fact that the
`coding-standard` files no longer exist (in case someone is upgrading
and currently extending from them).
Closes #81

Remove `babel` as the default parser

---

bower.json
package.json

Related to #121, update to match relevant changes to the default project structure.

Update project structure for Ember CLI 2.8.0

---

.eslintrc.js
blueprints/ember-cli-eslint/files/.eslintrc.js
blueprints/ember-cli-eslint/files/tests/.eslintrc.js
tests/dummy/.eslintrc.js

My OCD couldn't help itself 😀. 
I noticed we were being inconsistent with the use of property quotes in our `.eslintrc.js` files, so I standardized everything to no-quotes.
A lot of `.eslintrc.js` files in the wild seem to look this way -- my guess is due to the transition from `.eslintrc.json` a while back -- but FWIW the ESLint team appears to be [writing their `.js`'s quoteless](https://github.com/eslint/eslint/search?l=javascript&p=1&q=rules&type=Code&utf8=%E2%9C%93).

Remove quotes from properties in .eslintrc.js files

---

blueprints/ember-cli-eslint/index.js
node-tests/blueprints/ember-cli-eslint-test.js

jshintrc - ignore more

---

index.js

This reduced the command startup time by ~ 100ms.

Lazily require `broccoli-lint-eslint`.

---

package.json

As part of the work for ember-cli@2.13, all "built in" addons are being updated to use ember-cli-babel@6.
In this addons case, we do not need ember-cli-babel at all so removing the dep is simpler/better.

Remove ember-cli-babel dependency.

---

.travis.yml

This should hopefully fix the CI build, now that Node 8 `== stable`
/cc @rwjblue

CI: Adjust "yarn install" instruction

---

README.md
index.js

Allow passthrough of rulesDir option to broccoli-lint-eslint

---

index.js
package.json
yarn.lock

`semver`'s `satisfies` has somewhat bizarre issues around matching prerelease versions. In this case, we don't _really_ care what version you are using at all, we just want to check if you have a given dependency installed.
This updates to using a new API in ember-cli-version-checker to simply check if a given dep exists or not.
Fixes https://github.com/ember-cli/ember-cli-eslint/issues/214

Use dep.exists() to check for presence.

---

README.md
index.js

because https://github.com/emberjs/ember-qunit/pull/282 and https://github.com/emberjs/ember-mocha/pull/173

Extend test framework detection to `ember-qunit` and `ember-mocha`

---

node-tests/test.js
package.json
yarn.lock

Node 6 supports native Promises

Remove obsolete `es6-promise` dev dependency

---

.travis.yml
node-tests/test.js
testem.js

Use Chrome instead of PhantomJS to run tests

---

index.js

We want to check the `ember-qunit` dependency version of the host app, not of ourselves. This will make the project work with Yarn PnP.
https://github.com/emberjs/ember.js/blob/master/blueprints/test-framework-detector.js#L19 does is similarly, so I guess it's the actually correct way of doing it.

Fix `VersionChecker` construction

---

README.md

Per [typescript-eslint-parser's README](https://github.com/eslint/typescript-eslint-parser/blob/master/README.md), that project is no longer maintained and has been superseded by the @typescript-eslint/parser fork.

Link to @typescript/eslint-parser instead of typescript-eslint-parser
